version: '3'
services:
    node:
        build:
            context: ./
            dockerfile: ./docker/node/Dockerfile
        volumes:
            - ./src:/usr/src/app/src
            - ./public:/usr/src/app/public
        container_name: mhrise_dmgsimu_node
        ports:
            - "8080:8080"
    sqlite3:
        image: nouchka/sqlite3
        stdin_open: true
        tty: true
        volumes:
            - ./public/data:/root/db/
            - ./src/data:/tmp/data/
            - ./bin/in_container/data_import_in_sqlite3.sh:/tmp/bin/data_import.sh
        container_name: mhrise_dmgsimu_db