version: '3'
services:
    node:
        build:
            context: ./
            dockerfile: ./docker/node/Dockerfile
        volumes:
            - ./src:/usr/src/app/src
            - ./public:/usr/src/app/public
        container_name: mhrise_dmgsimu_node
        ports:
            - "8080:8080"